#!/bin/bash

echo ""
echo "=== 手動セットアップが必要な項目 ==="
echo ""
echo "[Obsidian Vault]"
echo ""
echo "  Claude Code の作業ログ機能を使用するには、Obsidian Vault のセットアップが必要です。"
echo ""
echo "  機能:"
echo "    - /log コマンド: 作業履歴を手動で記録"
echo "    - 自動ロギング: 一定条件で自動的に作業ログを記録"
echo ""
echo "  セットアップ手順:"
echo "    1. OneDrive 等の同期ツールで ~/ObsidianVault に Vault をコピー"
echo "    2. WSL の場合はシンボリックリンクを作成:"
echo "       ln -s /mnt/c/Users/<username>/ObsidianVault ~/ObsidianVault"
echo ""
echo "  補足:"
echo "    - 拡張機能や設定を変更した場合は .obsidian フォルダを各環境にコピー"
echo "    - メモの同期は Obsidian の git 拡張機能で行う"
echo ""
